version = 0.1

[default.deploy.parameters]
stack_name = "sam-pyappfunc-logonlogoff-test"
resolve_s3 = true
s3_prefix = "sam-pyappfunc-logonlogoff-test"
region = "ap-northeast-1"
profile = ""
capabilities = "CAPABILITY_IAM"
image_repositories = []
